# Generated by Django 5.1.2 on 2024-11-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sellerApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="termsandconditions",
            name="date_signed",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
