# Generated by Django 5.1.2 on 2024-11-16 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "sellerApp",
            "0003_alter_productuploadmethod_preferred_shipping_method_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seller",
            name="share_tax_identification_number",
        ),
    ]
