# Generated by Django 5.1.2 on 2024-11-16 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sellerApp", "0004_remove_seller_share_tax_identification_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seller",
            name="share_alternate_phone_number",
        ),
        migrations.RemoveField(
            model_name="seller",
            name="share_email",
        ),
        migrations.RemoveField(
            model_name="seller",
            name="share_phone_number",
        ),
    ]
