# Generated by Django 5.1.2 on 2024-11-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sellerApp", "0005_remove_seller_share_alternate_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="authorized_signatory_id",
            field=models.FileField(upload_to="media/documents/"),
        ),
        migrations.AlterField(
            model_name="document",
            name="business_registration_document",
            field=models.FileField(upload_to="media/documents/"),
        ),
        migrations.AlterField(
            model_name="document",
            name="proof_of_business_address",
            field=models.FileField(upload_to="media/documents/"),
        ),
        migrations.AlterField(
            model_name="document",
            name="tax_identification_document",
            field=models.FileField(upload_to="media/documents/"),
        ),
    ]
