# Generated by Django 5.1.2 on 2024-11-17 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sellerApp", "0007_document_authorized_signatory_id_thumbnail_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="authorized_signatory_id_thumbnail",
        ),
        migrations.RemoveField(
            model_name="document",
            name="business_registration_document_thumbnail",
        ),
        migrations.RemoveField(
            model_name="document",
            name="proof_of_business_address_thumbnail",
        ),
        migrations.RemoveField(
            model_name="document",
            name="tax_identification_document_thumbnail",
        ),
    ]
