# Generated by Django 5.1.2 on 2024-11-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sellerApp", "0009_remove_document_sellerapp_d_busines_d9a256_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="authorized_signatory_id_preview",
        ),
        migrations.RemoveField(
            model_name="document",
            name="business_registration_document_preview",
        ),
        migrations.RemoveField(
            model_name="document",
            name="proof_of_business_address_preview",
        ),
        migrations.RemoveField(
            model_name="document",
            name="tax_identification_document_preview",
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=[
                    "business_registration_document",
                    "business_registration_document_expiry_date",
                ],
                name="sellerApp_d_busines_d9a256_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["tax_identification_document", "tax_identification_document"],
                name="sellerApp_d_tax_ide_e15c9e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=[
                    "proof_of_business_address",
                    "proof_of_business_address_expiry_date",
                ],
                name="sellerApp_d_proof_o_e0131e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=[
                    "authorized_signatory_id",
                    "authorized_signatory_id_expiry_date",
                ],
                name="sellerApp_d_authori_fa2321_idx",
            ),
        ),
    ]
