# Generated by Django 5.1.2 on 2024-11-18 05:31

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sellerApp", "0010_remove_document_authorized_signatory_id_preview_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="alternate_mobile_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None
            ),
        ),
    ]
